### ISSUE TITLE
Swagger file is in HTML not JSON as Required

### ISSUE THREAD

**Issue by fergupa** [blue-prism/MicrosoftFlowAzureFunction#1]
Hello-

Thanks for putting this together.  However, when importing the 'swagger.json' file as  a custom connector (pages 8-9 in the guide), I get an error stating the file is not in JSON format:

![image](https://user-images.githubusercontent.com/22174512/68498360-af642e80-027c-11ea-892e-ea87547ad7de.png)

It looks like the file is in html, not JSON.  Please advise.  Thanks!

**Comment by ChrisHogan-BluePrism** [comment]
Can you let me know how you downloaded the JSON file?
If you simply used File/Save as when viewing this page:
https://github.com/blue-prism/MicrosoftFlowAzureFunction/blob/master/Blue-Prism-Generic.swagger.json

You will get the HTML page which shows the JSON embedded. You should click the Raw button to show the raw view. Then you should be able to download the proper JSON

**Comment by fergupa** [comment]
Thanks Chris- that works.

Quick question (if I can)- where do I find the host name for the function?

Paul Ferguson | Emerson | 314-910-8876
________________________________

**Comment by ChrisHogan-BluePrism** [comment]
The host is defined when you publish the Azure function. You can read about this on page 8 of the doc.

**Comment by fergupa** [comment]
Ok – so the url?

I think I’m pretty close but still get errors when trying to test.  Any chance we can jump on a webex?  If needed we can discuss a consulting charge.  Thanks!



Paul Ferguson |  +1 314 553 2665 | F +1 314 553 1376 | M +1 314 910 8876

**Comment by ChrisHogan-BluePrism** [comment]
FYI, a new version of this connector is here:

https://github.com/blue-prism/MicrosoftPowerPlatformConnector

It contains enhanced error resolution as well as dynamic discovery of services and the schema.

**Comment by manishtrivedi9** [comment]
is it possible to run a Process on my local desktop debug resource using this?

**Comment by EricWilson-BluePrism** [comment]
@manishtrivedi9 if you’re asking whether you can run a process on your local Blue Prism instance that leverages Microsoft Flow, the answer is yes.

**Comment by manishtrivedi9** [comment]
> @manishtrivedi9 if you’re asking whether you can run a process on your local Blue Prism instance that leverages Microsoft Flow, the answer is yes.

But how do my local BP instance  will be accessible to AzureFunction i deployed on azure?

**Comment by spartymants** [comment]
> > @manishtrivedi9 if you’re asking whether you can run a process on your local Blue Prism instance that leverages Microsoft Flow, the answer is yes.
> 
> But how do my local BP instance will be accessible to AzureFunction i deployed on azure?

@manishtrivedi9, in development if you're behind a firewall and using NAT you could use https://ngrok.com/ this will create a public end point and that can route the traffic to your machine.

**Comment by manishtrivedi9** [comment]
> > > @manishtrivedi9 if you’re asking whether you can run a process on your local Blue Prism instance that leverages Microsoft Flow, the answer is yes.
> > 
> > 
> > But how do my local BP instance will be accessible to AzureFunction i deployed on azure?
> 
> @manishtrivedi9, in development if you're behind a firewall and using NAT you could use https://ngrok.com/ this will create a public end point and that can route the traffic to your machine.

ngrok is blocked by my organization :-(

**Comment by manishtrivedi9** [comment]
Now I deployed a BP Azure VM and trying to trigger automation there. AzFunc and VM are on same ResourceGroup. I'm getting below error while trying to Test connector:
Status: 400
 "message": "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond",
